### ISSUE TITLE
how to I make an image fade in and out?

### ISSUE THREAD

**Issue by mephestopholes** [mephestopholes/semester-4-website#1]
@thomasjbradley 
This is my code for now, I want the image to fade in and out when the user hovers over it with the mouse. I did it with scale but that did not look the way I want it to. 

lines 141 to 159 in my main.css

.aura {
    height: 400px;
    position: absolute;
    right: 0;
    top: 0;
    opacity: 0;
    animation: glow 1500ms ease-in-out infinite;
}
@keyframes glow {
    0% {
        transform: opacity (0)
    }
    50% {
        transform: opacity (1)
    }
    100% {
        transform: opacity (0)
    }
}

**Comment by thomasjbradley** [comment]
`opacity` is definitely what you want, but don’t use `transform: opacity` that doesn’t exist. Just use `opacity: 1`, by itself.

**Comment by mephestopholes** [comment]
AWESOME! THANKS!!!
